CREATE TABLE account
(
    account_id   BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    userid       VARCHAR(50),
    password     VARCHAR(100),
    name         VARCHAR(50),
    phone_number VARCHAR(20),
    birth_date   date,
    token_weight BIGINT,
    activated    BOOLEAN,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);
COMMENT ON TABLE account IS '사용자 계정 정보';
COMMENT ON COLUMN account.activated IS '사용자 활성 유무';
COMMENT ON COLUMN account.birth_date IS '사용자 생년월일';
COMMENT ON COLUMN account.account_id IS '사용자 고유번호';
COMMENT ON COLUMN account.token_weight IS '사용자 토큰 가중';
COMMENT ON COLUMN account.phone_number IS '사용자 연락처';
COMMENT ON COLUMN account.name IS '사용자 이름';
COMMENT ON COLUMN account.userid IS '사용자 아이디';
COMMENT ON COLUMN account.password IS '사용자 비밀번호';

CREATE TABLE assignment
(
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institute_id  BIGINT                                  NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    reward_credit numeric(38, 2)                          NOT NULL,

    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT assignment_pkey PRIMARY KEY (assignment_id)
);
COMMENT ON TABLE assignment IS '과제 정보';
COMMENT ON COLUMN assignment.end_date IS '과제 종료일';
COMMENT ON COLUMN assignment.reward_credit IS '과제 수행 금액';
COMMENT ON COLUMN assignment.start_date IS '과제 시작일';
COMMENT ON COLUMN assignment.institute_id IS '과제 등록 학원';

CREATE TABLE assignment_submit
(
    assignment_submit_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assignment_assignment_id BIGINT,
    assignment_submit_type   VARCHAR(20)                             NOT NULL,
    account_id               BIGINT,
    comment                  VARCHAR(200)                            NOT NULL,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255),
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT assignment_submit_pkey PRIMARY KEY (assignment_submit_id)
);
COMMENT ON TABLE assignment_submit IS '과제 제출';
COMMENT ON COLUMN assignment_submit.assignment_submit_type IS '과제 제출 상태';
COMMENT ON COLUMN assignment_submit.comment IS '코멘트';

CREATE TABLE badge
(
    badge_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institute_id BIGINT,
    badge_type   VARCHAR(20)                             NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  OID,
    recipient    BIGINT,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT badge_pkey PRIMARY KEY (badge_id)
);
COMMENT ON TABLE badge IS '배지 정보';
COMMENT ON COLUMN badge.badge_id IS '배지 고유키';
COMMENT ON COLUMN badge.institute_id IS '배지 수여 학원';
COMMENT ON COLUMN badge.recipient IS '배지 취득자';
COMMENT ON COLUMN badge.badge_type IS '배지 코드';
COMMENT ON COLUMN badge.title IS '배지 제목';
COMMENT ON COLUMN badge.description IS '배지 설명';

CREATE TABLE budget
(
    budget_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    institute_id  BIGINT                                  NOT NULL,
    start_date    date                                    NOT NULL,
    end_date      date                                    NOT NULL,
    budget_amount numeric(38, 2)                          NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT budget_pkey PRIMARY KEY (budget_id)
);
COMMENT ON TABLE budget IS '예산 정보';
COMMENT ON COLUMN budget.budget_amount IS '예산 금액';
COMMENT ON COLUMN budget.end_date IS '예산 종료일';
COMMENT ON COLUMN budget.start_date IS '예산 시작일';
COMMENT ON COLUMN budget.institute_id IS '예산 등록 학원';

CREATE TABLE credit
(
    credit_id  BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL,
    account_id BIGINT,
    balance    numeric(38, 2),
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT credit_pkey PRIMARY KEY (credit_id)
);
COMMENT ON TABLE credit IS '사용자 포인트 정보';
COMMENT ON COLUMN credit.balance IS '잔액';
COMMENT ON COLUMN credit.credit_id IS '사용자 포인트 고유번호';

CREATE TABLE credit_detail
(
    credit_detail_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_id            BIGINT,
    budget_id            BIGINT,
    assignment_submit_id BIGINT,
    in_balance           numeric(38, 2),
    out_balance          numeric(38, 2),
    before_balance       numeric(38, 2),
    after_balance        numeric(38, 2),
    comment              VARCHAR(200),
    created_by           VARCHAR(255),
    updated_by           VARCHAR(255),
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT credit_detail_pkey PRIMARY KEY (credit_detail_id)
);
COMMENT ON TABLE credit_detail IS '사용자 포인트 내역 정보';
COMMENT ON COLUMN credit_detail.after_balance IS '최종 잔액';
COMMENT ON COLUMN credit_detail.before_balance IS '이전 잔액';
COMMENT ON COLUMN credit_detail.in_balance IS '입금';
COMMENT ON COLUMN credit_detail.out_balance IS '출금';
COMMENT ON COLUMN credit_detail.assignment_submit_id IS '과제 수행';
COMMENT ON COLUMN credit_detail.budget_id IS '예산';
COMMENT ON COLUMN credit_detail.credit_detail_id IS '사용자 포인트 내역 고유번호';
COMMENT ON COLUMN credit_detail.comment IS '코멘트';

CREATE TABLE franchisor
(
    franchisor_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                         VARCHAR(20),
    owner                        VARCHAR(20),
    tel                          VARCHAR(20),
    zip                          VARCHAR(20),
    addr1                        VARCHAR(200),
    addr2                        VARCHAR(200),
    business_registration_number VARCHAR(20),
    created_by                   VARCHAR(255),
    updated_by                   VARCHAR(255),
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT franchisor_pkey PRIMARY KEY (franchisor_id)
);
COMMENT ON TABLE franchisor IS '가맹점 정보';
COMMENT ON COLUMN franchisor.business_registration_number IS '사업자등록 번호';
COMMENT ON COLUMN franchisor.name IS '학원명';
COMMENT ON COLUMN franchisor.owner IS '대표자명';
COMMENT ON COLUMN franchisor.tel IS '연락처';
COMMENT ON COLUMN franchisor.zip IS '우편번호';
COMMENT ON COLUMN franchisor.addr1 IS '주소1';
COMMENT ON COLUMN franchisor.addr2 IS '주소2';

CREATE TABLE institute
(
    institute_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                         VARCHAR(20),
    owner                        VARCHAR(20),
    tel                          VARCHAR(20),
    zip                          VARCHAR(20),
    addr1                        VARCHAR(200),
    addr2                        VARCHAR(200),
    business_registration_number VARCHAR(20),
    created_by                   VARCHAR(255),
    updated_by                   VARCHAR(255),
    created_at                   TIMESTAMP WITHOUT TIME ZONE,
    updated_at                   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT institute_pkey PRIMARY KEY (institute_id)
);
COMMENT ON TABLE institute IS '학원정보';
COMMENT ON COLUMN institute.business_registration_number IS '사업자등록 번호';
COMMENT ON COLUMN institute.name IS '학원명';
COMMENT ON COLUMN institute.owner IS '대표자명';
COMMENT ON COLUMN institute.tel IS '연락처';
COMMENT ON COLUMN institute.zip IS '우편번호';
COMMENT ON COLUMN institute.addr1 IS '주소1';
COMMENT ON COLUMN institute.addr2 IS '주소2';


ALTER TABLE account
    ADD CONSTRAINT account_userid_key UNIQUE (userid);

ALTER TABLE credit
    ADD CONSTRAINT credit_account_id_key UNIQUE (account_id);

ALTER TABLE credit_detail
    ADD CONSTRAINT credit_detail_assignment_submit_id_key UNIQUE (assignment_submit_id);

CREATE TABLE account_authority
(
    account_id     BIGINT       NOT NULL,
    authority_name VARCHAR(255) NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT account_authority_pkey PRIMARY KEY (account_id, authority_name)
);
COMMENT ON TABLE account_authority IS '사용자 권한 정보';

CREATE TABLE account_children
(
    parent_id   BIGINT NOT NULL,
    children_id BIGINT NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT account_children_pkey PRIMARY KEY (children_id, parent_id)
);
COMMENT ON TABLE account_children IS '사용자 자녀 정보';

CREATE TABLE account_franchisor
(
    account_id    BIGINT NOT NULL,
    franchisor_id BIGINT NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT account_franchisor_pkey PRIMARY KEY (account_id, franchisor_id)
);
COMMENT ON TABLE account_franchisor IS '사용자 가맹점 정보';

CREATE TABLE account_institute
(
    account_id   BIGINT NOT NULL,
    institute_id BIGINT NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT account_institute_pkey PRIMARY KEY (account_id, institute_id)
);
COMMENT ON TABLE account_institute IS '사용자 학원 정보';

CREATE TABLE authority
(
    authority_name VARCHAR(50) NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT authority_pkey PRIMARY KEY (authority_name)
);
COMMENT ON TABLE authority IS '사용자 권한';

CREATE TABLE institute_children
(
    children_id  BIGINT NOT NULL,
    institute_id BIGINT NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT institute_children_pkey PRIMARY KEY (children_id, institute_id)
);
COMMENT ON TABLE institute_children IS '학원 등록 자녀 정보';

ALTER TABLE account_children
    ADD CONSTRAINT fk5v4oqiwnc560sw9cg8impy5lv FOREIGN KEY (children_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE credit_detail
    ADD CONSTRAINT fk5ywl0v8b9t3pnua4cjs58xigm FOREIGN KEY (assignment_submit_id) REFERENCES assignment_submit (assignment_submit_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_franchisor
    ADD CONSTRAINT fk9t7em4mv0s88qmc1nfuelm3di FOREIGN KEY (account_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_authority
    ADD CONSTRAINT fkaffih17qsu6xtryrgtal364ap FOREIGN KEY (authority_name) REFERENCES authority (authority_name) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_institute
    ADD CONSTRAINT fkasex6eyox9j3u9tat9e9lwlcb FOREIGN KEY (account_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_franchisor
    ADD CONSTRAINT fkc1wtdoldhs9w7r7rwpq5640jv FOREIGN KEY (franchisor_id) REFERENCES franchisor (franchisor_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE assignment_submit
    ADD CONSTRAINT fkd81w0qjkjsy8bo7guna77avcn FOREIGN KEY (assignment_assignment_id) REFERENCES assignment (assignment_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE institute_children
    ADD CONSTRAINT fkd9f66kh29l539v8krwitvstc7 FOREIGN KEY (institute_id) REFERENCES institute (institute_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE institute_children
    ADD CONSTRAINT fkedr8xsmwhww48x8yqsfftxnih FOREIGN KEY (children_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE budget
    ADD CONSTRAINT fkfk0kqhvd85pktx0g08fc5nd1r FOREIGN KEY (institute_id) REFERENCES institute (institute_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE credit_detail
    ADD CONSTRAINT fkh3l5tnddxyria9hx5ibpkn9ep FOREIGN KEY (credit_id) REFERENCES credit (credit_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE badge
    ADD CONSTRAINT fkh6qr5hf8uhv01wtacdl84kxhh FOREIGN KEY (institute_id) REFERENCES institute (institute_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE badge
    ADD CONSTRAINT fkhqwnkd2ynu103jvheubp9opt3 FOREIGN KEY (recipient) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE assignment
    ADD CONSTRAINT fkkl2jjersl5nnq5rmowcyhxeu1 FOREIGN KEY (institute_id) REFERENCES institute (institute_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_children
    ADD CONSTRAINT fkl6ejveis3y31pci1duey99unw FOREIGN KEY (parent_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_institute
    ADD CONSTRAINT fkouiolw72f26qxre7y483vim6p FOREIGN KEY (institute_id) REFERENCES institute (institute_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE credit_detail
    ADD CONSTRAINT fks7910ry9pv210at3n1afsqqg9 FOREIGN KEY (budget_id) REFERENCES budget (budget_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE account_authority
    ADD CONSTRAINT fksglqde2oirunehlexcjkt68eb FOREIGN KEY (account_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE assignment_submit
    ADD CONSTRAINT fksrgstulm19594rxb95l8ybcc2 FOREIGN KEY (account_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE credit
    ADD CONSTRAINT fkt7958tp3eu6xsep7y9tsdqko FOREIGN KEY (account_id) REFERENCES account (account_id) ON UPDATE NO ACTION ON DELETE NO ACTION;