server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration/postgres,classpath:db/seed/local

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  secret: aGVsbG8gd29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2EK # fill in base64 [command: echo {plain_text} | base64]
  refresh-token-secret: d29ybGQgbXkgbmFtZSBpcyBzc29uZyBoYWhhaGFoYWhhaGFoYSBydXJ1cnVydXJ1cnVydXJ1ZHNmc2Rmc2Rmc2Rmc2FkCg== # it must be different from the access key secret
  access-token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 86400

dgs:
  graphql:
    path: "/graphql"
    introspection:
      enabled: true
    schema-json:
      enabled: true
      path: "/schema.json"
    schema-locations: "classpath*:schema/**/*.graphql*"
    graphiql:
      enabled: true
      title: "SMARTER-POINTMARKET GraphiQL"
      path: "/graphiql"

graphql:
  voyager:
    enabled: true
    basePath: /
    mapping: /voyager
    endpoint: /graphql

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com:
      ksmarter:
        pointmarket: debug